version: 1
plugin:
  id: seaf_plugin
  name: SEAF Plugin
  description: Dynamic menu integration with modular config includes
  runtimeVersion: 0.5.11
python:
  executable: python3
  requirementsFile: ../python/requirements.txt
  requiredModules:
    - lib.io
  scriptsDir: ../python/scripts
logging:
  level: info
  extendedDebug: true
  includePayload: true
  output: both
  filePath: ../logs/seaf-plugin.log
update:
  enabled: true
  mode: ssh_git
  repo: ""
  gitRepoSsh: git@github.com:koa73/seaf-plugin-runtime.git
  gitRef: master
  assetPath: release/out/seaf-plugin-runtime.tar.gz
  expectedMinVersion: 0.2.6
  ssh:
    privateKeyPath: ../keys/seaf-plugin-runtime
    publicKeyPath: ../keys/seaf-plugin-runtime.pub
  assetName: seaf-plugin-runtime.tar.gz
  tag: ""
  apiBaseUrl: https://api.github.com
events:
  configFile: events.yaml
includes:
  menus:
    main: main_menu.yaml
    context: context_menu.yaml
  events:
    commands: events.yaml
